name: 03 - Workflow Runners

on: push

jobs:
    ubuntu-rcho:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on:"
                uname -a
                echo: "The runner OS is $RUNNER_OS"