name: 06 - contexts

on: push

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Informaiton
        run: |
          echo "event name": ${{ github.event_name }}
          echo "ref": ${{ github.ref }}
          echo "sha": ${{ github.sha }}
          echo "Actor": ${{ github.actor }}
          echo "Workflow": ${{ github.workflow }}
          echo "Run ID": ${{ github.run_id }}
          echo "Run Number": ${{ github.run_number }}
      - name: Retrieve Variables
        run: |
          echo "Variable Value": ${{ vars.MY_VAR}}

