name: 07 - using expressions

on: 
  push:
  workflow_dispatch:
    inputs: 
      debug:
        description: Enable debug mode
        type: boolean
        default: false
    

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
          - name: '[debug] Print information'
            if: ${{ inputs.debug }}
            run: |
              echo "Triggered by event: ${{ github.event_name }}"
              echo "branch: ${{ github.ref }}"
              echo "commit sha: ${{ github.sha }}"
              echo "Runner OS: ${{ runner.os }}"
          - name: '[debug] Truggered from main'
            if: ${{ github.ref == 'refs/heads/main' && inputs.debug }}
            run: echo "This debug run was triggered from main branch"
          - name:  echo "Hello World"
            run: echo "Hello, World!" 